<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7aT3b6I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7aT3b6I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7aT3b6I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7aT3b6I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7aT3b6I\App_KernelDevDebugContainer([
    'container.build_hash' => '7aT3b6I',
    'container.build_id' => '46e313e5',
    'container.build_time' => 1591563946,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7aT3b6I');
